### ISSUE TITLE
Can you elaborate on how your fork is different?

### ISSUE THREAD

**Issue by jeffbski** [redbadger/immutable-cursor#2]
I read the issue linked in the readme but don't fully understand how your fork will be different from Immutable.js. 

Can you elaborate on it with some good examples in the README?

That will really help me understand what you are trying to accomplish and how your version will be different from Immutable.js.

I guess it would be helpful to also explain whether one can still use Immutable.js along side of this and whether the cursor is the only thing you are forking, etc.

I think spelling these out clearly will help people understand your project.

**Comment by jameshopkins** [comment]
Hi @jeffbski. Thanks for the feedback. I've just released `0.0.2` which includes updated documentation as to why it's different. I suspect you may have seen the README before I released this.

That's a good idea to point out how to use it in conjunction with Immutable.js - will fix that now!

**Comment by jameshopkins** [comment]
Hi @jeffbski. Please see https://github.com/redbadger/immutable-cursor#relationship-with-immutablejs for details on how to use this cursor with Immutable.js. If you still have any questions, please let me know.

**Comment by jeffbski** [comment]
Great. I think that helps much. I look forward to trying our your cursor implementation.
