### ISSUE TITLE
Get some of the immutability back

### ISSUE THREAD

**Issue by charypar** [redbadger/immutable-cursor#5]
I thought about what the cursor is doing a lot, and I think what we really want is a middle ground. That is:
- it is ok for cursors to show you an immutable reality during the entire render phase no matter what you do
- it is _not_ ok for update transactions done in one render cycle not to serialise - e.g. two updates to an array of `[1, 1]` doing an increment on first and second element respectively cannot result in `[1, 2]` or `[2, 1`, they have to result in `[2, 2]`

I think the way to achieve that is for cursors to expand all the various updates you can do to them (`set`, `update`, etc.) to a single primitive: an update function of the signature `old value -> new value`. The cursor wraps this function with a function that fetches the current value from the entire state data structure and applies it back to it, resulting in a function you can run as an update against the entire state tree.

To synchronise those updates we can use a JS equivalent of a clojure `atom` (as helpfully pointed out by @leebyron), which would be a wrapped `var` that supports the `update` semantics, e.g.:

``` javascript

const myAtom = atom(someImmutableData);

myAtom.val() // oldVal, i.e. someImmutableData
myAtom.transact((oldVal) -> ...; return newVal);
myAtom.val() // newVal
```

You can then use those two things to achieve the same update semantics that you have now, but without sacrificing the immutability during the render cycle.

Hope that makes sense :)

**Comment by leebyron** [comment]
Yes! Thank you for expanding on this, this makes perfect sense. This would allow immutable cursors to shed their mutation APIs and only keep read APIs. The function body of `transact` would get the actual underlying value.

The next step to follow is how to connect this back to cursors such that a cursor's `transact` can trigger the atom's `transact` in a way that could be batched.

**Comment by glenjamin** [comment]
Might be useful to look at pairing with https://github.com/cjohansen/js-atom - which was written by a Clojure programmer who missed having atoms.

**Comment by charypar** [comment]
@leebyron I think the connection back to cursor is pretty easy.The difference is the cursor doesn't call you back with a new value of the entire structure, but with a function that can turn a current value of it to a new value. Roughly something like this:

``` javascript
const atom = atom(myData);
atom.get() // => myData

// 'change' is "(oldVal) => newVal" created by the cursor by 
// wrapping the local update of a same signature supplied by the user
const onUpdate = (change) => {
  atom.transact(change); 
  React.render(<Component data={cursor(atom.get(), onUpdate)} />, container);
};

React.render(<Component data={cursor(atom.get(), onUpdate)} />, container)
```

Cursors need to be able to translate mutation API calls to the `update` primitive and be able to wrap it with global "data path context".

That should be it, I think

**Comment by charypar** [comment]
@glenjamin Thanks! seems perfect

**Comment by ds300** [comment]
Mind if I pop in for a shameless plug of [havelock](https://github.com/ds300/havelock)? If I understand the problem correctly, it does all this and more. Check it out:

``` javascript
import { atom } from 'havelock'
import { fromJS } from 'immutable'

// first we need to define a cursor implementation for immutable.js
function cursor(keyPath) {
    return {
        get: (parentValue) => parentValue.getIn(keyPath),
        set: (parentValue, newValue) => parentValue.setIn(keyPath, newValue)
    }
}

const root = atom(fromJS({things: [1,2,3]}));
const firstThing = root.lens(cursor(['things', 0]));
const thirdThing = root.lens(cursor(['things', 2]));

console.log(firstThing.get(), thirdThing.get()) //$
// $> 1 3

firstThing.swap(x => x + 1);
thirdThing.swap(x => x + 1);

console.log(firstThing.get(), thirdThing.get()) //$
// $> 2 4
console.log(root.get()) //$
// $> Map { "things": List [ 2, 2, 4 ] }
```

I know it's probably not exactly the API you're looking for, but nothing that a bit of wrapping and munging can't fix.

**Comment by charypar** [comment]
@ds300 I think what you described is the current behaviour of `immutable-cursor`. This part:

``` js
firstThing.swap(x => x + 1);
thirdThing.swap(x => x + 1);

console.log(firstThing.get(), thirdThing.get()) //$
// $> 2 4
```

Is the problematic one - it basically means `firstThing` and `thirdThing` are mutable. What we'd expect is this:

``` js
firstThing.swap(x => x + 1);
thirdThing.swap(x => x + 1);

console.log(firstThing.get(), thirdThing.get()) //$
// $> 1 3
console.log(root.get()) //$
// $> Map { "things": List [ 2, 2, 4 ] }
```

i.e. atom got updated fully, cursors stayed immutable.

**Comment by ds300** [comment]
Apologies for my misunderstanding. So you want state updates to be cached (as functions?) and remain invisible until after the render phase when they get 'applied' and the cursors will reflect the new state? 

I mean, that's doable, but wouldn't it trigger another render immediately, leading to the possibility of infinite loops?

**Comment by charypar** [comment]
@ds300 We want cursors to be really immutable. Forever, like values should be. Changes are invisible to the render phase, because they require new cursors based on the new state to be passed down the component tree. Updates done on cursors get applied immediately (to the root atom!), but it's up to you when you render using the current state in the atom to construct new root cursor (various batching strategies would be applicable here). The only mutability in the entire system is in the root atom, everything else is immutable.

**Comment by jameshopkins** [comment]
This update is being worked on in https://github.com/redbadger/immutable-cursor/pull/9
