### ISSUE TITLE
.withMutations() doesn't work when mutations are performed on a derived cursor of the transient, mutable copy 

### ISSUE THREAD

**Issue by jameshopkins** [redbadger/immutable-cursor#7]
``` js
const data = Immutable.fromJS({
  a: 'wahey',
  b: 'moo',
  c: []
});

const c1 = Cursor.from(data, onChange);
const c2 = c1.withMutations(m => m.get('c').push('hello'));
```

yields:

``` js
{a: 'wahey', b: 'moo', c: []}
```

when I would expect:

``` js
{a: 'wahey', b: 'moo', c: ['hello']}
```

**Comment by charypar** [comment]
I'm not sure you can use `withMutations` to change things nested in the map. The mutable copy is of the map only, not everything stored in it. The documentation also points out that:

> Note: Not all methods can be used on a mutable collection or within withMutations! Only set and merge may be used mutatively.

The point of `withMutations` is to speed up a series of `set`s, not all the calls of all the mutative APIs on everything stored within. I'm not even sure how that would work :)
